# Generated by Django 4.1.4 on 2022-12-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytype',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
