# Generated by Django 4.1.4 on 2022-12-27 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary_app', '0002_alter_entrytype_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytype',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
